name: Release

on:
  push:
    branches:
    - master

jobs:
  release:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x]
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Monkey patch electron-builder
      run: sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
      shell: bash
    - name: Test
      run: yarn tests
      env:
        CI: true
    - name: Tag
      run: |
        TAG=$(node -p -e "require('./package.json').version") && \
        curl -s -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- { "ref": "$GITHUB_REF/v$TAG", "sha": "$GITHUB_SHA" }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      run: yarn release
      env:
        CI: true
        CSC_LINK: ${{ secrets.macOSDeveloperCertificate_base64 }}
        CSC_KEY_PASSWORD: ${{ secrets.macOSDeveloperCertificate_password }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_S3_BUCKET: ${{ secrets.LODE_RELEASES_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_PUBLISHER_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PUBLISHER_SECRET }}
