name: Tag

on:
  push:
    branches:
    - develop

jobs:
  release:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x]
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Tag
      run: |
        VERSION=$(node -p -e "require('./package.json').version")
        NOTES=$(cat support/release-notes.md)
        echo "$VERSION"
        echo "$NOTES"
        PAYLOAD=$(cat <<EOF
        {
          "tag_name": "v$VERSION",
          "target_commitish": "master",
          "name": "$VERSION",
          "body": "$NOTES",
          "draft": true,
          "prerelease": false
        }
        EOF
        )
        echo "$PAYLOAD"
        curl -X POST \
          https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
          -H 'Content-Type: application/json' \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d "$PAYLOAD"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
