name: Node CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
    
jobs:
  build:
    name: Test and build using node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x]
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn tests
      env:
        CI: true
    - name: Build
      run: yarn build
      env:
        CI: true
